# Generated by Django 6.1 on 2026-08-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_dishtype_dish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cook',
            options={'verbose_name': 'cook', 'verbose_name_plural': 'cooks'},
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dishes', models.ManyToManyField(related_name='ingredients', to='kitchen.dish')),
            ],
        ),
    ]
