# Generated by Django 6.1 on 2026-08-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_alter_cook_options_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='dishes',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='kitchen.ingredient'),
        ),
    ]
